site_name: pysitemaps
site_description: Python Package to Create, Manipulate and Analyze Website Sitemaps
site_author: Faisal Shahzad

site_url: https://pysitemaps.pages.dev

repo_url: https://github.com/serpwings/pysitemaps
edit_uri: blob/main/docs/

nav:
  - Home: index.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - toc:
      permalink: True
  - attr_list
  
theme: readthedocs

copyright: © Copyright 2022 Faisal Shahzad